export { default as BagSVG } from "./bag";
export { default as ChevronDownSVG } from "./chevron-down";
export { default as DotsSVG } from "./dots";
export { default as HeartSVG } from "./heart";
export { default as PauseSVG } from "./pause";
export { default as PlaySVG } from "./play";
export { default as ReplySVG } from "./reply";
export { default as ShirtSVG } from "./shirt";
export { default as TimesSVG } from "./times";
